apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: github-actions-eks
  namespace: flux-system

spec:
  imageRepositoryRef:
    name: github-actions-eks

  filterTags:
    pattern: '^(\d{8})-(\d{6})-[a-f0-9]{7}$'
    extract: '$1$2'

  policy:
    numerical:
      order: asc