apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "flask-app.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "flask-app.name" . }}

    spec:
      # serviceAccountName: aws-load-balancer-controller

      containers:
        - name: flask-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}