replicaCount: 2

image:
  repository: rajeshdangi/github-actions-eks

  # {"$imagepolicy": "flux-system:github-actions-eks:tag"}
  tag: "20260720-112054-3a355e6"

  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: alb

resources: {}

serviceAccount:
  create: false