replicaCount: 2
image:
  repository: rajeshdangi/github-actions-eks
  tag: "20260723-055544-f763e78" # {"$imagepolicy": "flux-system:github-actions-eks:tag"}
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
ingress:
  enabled: true
  className: alb
resources: {}
serviceAccount:
  create: false
